### ISSUE TITLE
If I pause How do I show Subtitle  ?

### ISSUE THREAD

**Issue by poholo** [ottersoftware/AVSynchronizedLayerTest#1]
I am glad find AVSynchronizedLayerDemo
 let Player play the movie, AVPlayer show video &  audio and AVSynchronizedLayer show animaitons & subtitles?

**Comment by ottersoftware** [comment]
The subtitles should show in the AVSynchronisedLayer so pausing the video won't matter since the subtitles for the time the video is paused at will be showing.

However, in more recent versions of iOS it's possible for subtitles to be shown automatically using AVPlayerItem's selectMediaOption:inMediaSelectionGroup:

Get the AVMediaCharacteristicLegible selection group from the AVAsset, investigate the available options, and then use the above method to select which subtitle option you would like to use.

**Comment by poholo** [comment]
Add subtitle code 
`
- (CATextLayer *)addTitle:(NSString *)title font:(UIFont *)font frame:(CGRect)frame showTime:(CGFloat)timeInterval{
    CATextLayer *textLayer = [CATextLayer layer];
    textLayer.frame = frame;
    
    //set text attributes
    textLayer.foregroundColor = [UIColor whiteColor].CGColor;
    textLayer.alignmentMode = kCAAlignmentJustified;
    textLayer.wrapped = YES;
    [textLayer setAlignmentMode:kCAAlignmentCenter];

    //set layer font
    CFStringRef fontName = (__bridge CFStringRef)font.fontName;
    CGFontRef fontRef = CGFontCreateWithFontName(fontName);
    textLayer.font = fontRef;
    textLayer.fontSize = font.pointSize;
    CGFontRelease(fontRef);
    
    //choose some text
    NSString *text = title;
    //set layer text
    textLayer.string = text;
    textLayer.opacity = 0.0f;
    
    [self showTextLayer:textLayer showTime:timeInterval];
    return textLayer;

}
`
Add subtitle on AVSynchronizedLayer
`AVPlayerItem *item = [AVPlayerItem playerItemWithAsset:_compositon];
    playerItem.videoComposition = _videoComposition;

    if(self.audioAsset) {
        playerItem.audioMix = _audioMix;
    }

    AVSynchronizedLayer * avSynchronizedLayer = [AVSynchronizedLayer synchronizedLayerWithPlayerItem:item];
avSynchronizedLayer.frame = CGRectMake(0, 0, 480, 480);

 CATextLayer * textLayer = [self addTitle:photo.textStr font:font frame:CGRectMake(240 - size.width / 2.0, 240 - size.height / 2.0, size.width, size.height) showTime:timeInterval.floatValue];
[avSynchronizedLayer addSublayer:textLayer];
`
Synchronized to AVPlayerItem to play
`
 _avsynchronizedLayer.frame = CGRectMake(0, 0, self.frame.size.width, self.frame.size.height);
    [self.layer insertSublayer:_avsynchronizedLayer above:self.layer];
`

So I can play Subtitle on AVPlayer , but I think is it have better smartly method ?

**Comment by ottersoftware** [comment]
My apologies if I don't completely understand what you are asking but the theory behind the code is that you display the subtitle text in a CATextLayer which is a child layer of an AVSynchronizedLayer. The AVPlayer is effectively a different object and display the video frames. For a custom player you usually use an AVPlayerLayer to display the video in your user interface and then on top of the AVPlayerLayer you have the AVSynchronizedLayer which contains the CATextLayer.

Sorry, I'm probably explaining it really badly!

However, as I said in my previous reply, more recent versions of iOS allow you to display subtitles 'natively' without having to go through all of this.
